#pragma once

#define MAP_MAX_WIDTH 64
#define MAP_MAX_HEIGHT 32
#define MAP_DATA_MAX_SIZE (MAP_MAX_WIDTH * MAP_MAX_HEIGHT)

#define BORDER_CHAR_HORIZONTAL '-'
#define BORDER_CHAR_VERTICAL '|'
#define PLAYER_CHAR '@'

#define INPUT_FIELD_SELECTION_COUNT 4
#define INPUT_FIELD_SELECTION_HEIGHT 1

#define TEXT_FIELD_MAX_WIDTH 64
#define INPUT_FIELD_MAX_HEIGHT (INPUT_FIELD_SELECTION_COUNT * INPUT_FIELD_SELECTION_HEIGHT)

#define MIN_TERMINAL_WIDTH (MAP_MAX_WIDTH + TEXT_FIELD_MAX_WIDTH + 3)
#define MIN_TERMINAL_HEIGHT (MAP_MAX_HEIGHT + 2)

#define TEXT_FIELD_MAX_LENGTH (TEXT_FIELD_MAX_WIDTH * (MAP_MAX_HEIGHT - INPUT_FIELD_MAX_HEIGHT - 1))
#define INPUT_FIELD_MAX_LENGTH (TEXT_FIELD_MAX_WIDTH * INPUT_FIELD_MAX_HEIGHT)

typedef struct Map
{
    int playerStartX;
    int playerStartY;
    char data[MAP_MAX_HEIGHT][MAP_MAX_WIDTH];
} Map;

typedef struct Player
{
    int x;
    int y;
} Player;
